version: '3.2'

services:
  spyder:

    container_name: python_developer_test_task

    build:
      context: ./build/

    image: web_crawler

    volumes:
      - /etc/passwd:/etc/passwd:cached
      - /etc/group:/etc/group:cached
      - .:/app:cached

    command: python3 ./app/spyder.py get http://tass.ru/ural --depth 2
