version: '3.2'

services:
  spyder:

    container_name: python_developer_test_task

    build:
      context: ./build/

    image: web_crawler

    volumes:
      - /app/:/app/

    command: python3 spyder.py get http://tass.ru/ural --depth 2
